import {scopeEnum} from "../util/scope-enum";

export enum BLITZ_EVENTS {
	BEFORE_INSERT = "BEFORE_INSERT",
	AFTER_INSERT = "AFTER_INSERT",
	BEFORE_UPDATE = "BEFORE_UPDATE",
	AFTER_UPDATE = "AFTER_UPDATE",
	BEFORE_DELETE = "BEFORE_DELETE",
	AFTER_DELETE = "AFTER_DELETE"
}

scopeEnum(BLITZ_EVENTS, "BLITZ_EVENTS");
